# Generated by Django 6.0.4 on 2026-04-08 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_image_content_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='perceptual_hash',
            field=models.CharField(blank=True, db_index=True, help_text='Perceptual hash for visual similarity detection', max_length=16),
        ),
    ]
