# Generated by Django 6.0.4 on 2026-04-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_image_perceptual_hash"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_title", models.CharField(default="ExifTree", max_length=255)),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        default="Browse photography through the gear that made it.",
                        max_length=255,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "site configuration",
                "verbose_name_plural": "site configuration",
            },
        ),
    ]
