# Generated by Django 6.0.4 on 2026-04-08 19:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_site_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="image",
            name="ai_description",
            field=models.TextField(
                blank=True, help_text="AI-generated description of the image"
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="ai_title",
            field=models.CharField(
                blank=True, help_text="AI-generated artistic title", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="ai_prompt",
            field=models.TextField(
                blank=True,
                default="Describe this photograph in 2-3 sentences. Focus on the subject, mood, composition, and lighting. Be concise and evocative.",
                help_text="Prompt sent to the AI for image descriptions",
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="openai_api_key",
            field=models.CharField(
                blank=True,
                help_text="OpenAI API key for AI image descriptions",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="images", to="core.tag"
            ),
        ),
    ]
