# Generated by Django 6.0.4 on 2026-04-09 04:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_add_analytics_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        help_text="State/province/admin region",
                        max_length=255,
                    ),
                ),
                ("country_code", models.CharField(db_index=True, max_length=2)),
                ("country", models.CharField(max_length=255)),
                ("continent", models.CharField(db_index=True, max_length=20)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "cities",
                "ordering": ["continent", "country", "name"],
            },
        ),
        migrations.AddField(
            model_name="image",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="images",
                to="core.city",
            ),
        ),
    ]
