# Generated by Django 6.0.4 on 2026-04-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_city_image_city"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="image",
            index=models.Index(
                fields=["visibility", "is_processing", "upload_date"],
                name="core_image_visibil_c9666e_idx",
            ),
        ),
    ]
