# Generated by Django 6.0.4 on 2026-04-08 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="date",
            field=models.DateField(
                blank=True,
                help_text="Optional display date (e.g. date of shoot). Defaults to creation date.",
                null=True,
            ),
        ),
    ]
